import { defineField, defineType, type StringOptions } from "sanity";

import { VariantSelectInput } from "../../../components/VariantSelectInput";
import { i18nValue } from "../../previewI18n";

/**
 * Header / Hero block for the page-builder. Reuses the SectorHeader renderer,
 * which carries seven on-brand layouts sharing one content model (title,
 * subtitle, two buttons, hero media, colour profile). The layout is picked
 * visually via the thumbnail grid (VariantSelectInput). More header families
 * (initiative type1–4, etc.) can be folded in later behind the same field.
 */
export const headerBlock = defineType({
  name: "headerBlock",
  title: "Header / Hero",
  type: "object",
  fields: [
    defineField({
      name: "enabled",
      title: "Show this section",
      description: "Turn the block off without deleting it.",
      type: "boolean",
      initialValue: true,
    }),
    defineField({
      name: "layout",
      title: "Layout",
      type: "string",
      components: { input: VariantSelectInput },
      options: {
        // Must match the SectorHeaderLayout union in the renderer.
        list: [
          { title: "Split", value: "split" },
          { title: "Centered", value: "centered" },
          { title: "Side by side", value: "sideBySide" },
          { title: "Overlay", value: "overlay" },
          { title: "Showcase", value: "showcase" },
          { title: "Spotlight", value: "spotlight" },
          { title: "Masthead", value: "masthead" },
        ],
        // Thumbnails generated by scripts/generate-block-thumbnails.mjs.
        // `thumbBase` is a custom option read by VariantSelectInput.
        thumbBase: "/static/blocks/headerBlock",
      } as StringOptions,
      initialValue: "split",
    }),
    defineField({
      name: "title",
      title: "Title",
      type: "internationalizedArrayString",
    }),
    defineField({
      name: "subtitle",
      title: "Subtitle",
      type: "internationalizedArrayText",
    }),
    defineField({
      name: "primaryCta",
      title: "Primary button",
      type: "cta",
    }),
    defineField({
      name: "secondaryCta",
      title: "Secondary button",
      type: "cta",
    }),
    defineField({
      name: "media",
      title: "Hero image or video",
      type: "imageWithAlt",
    }),
    defineField({
      name: "pageColor",
      title: "Band colour (dark)",
      description: "The dark background of the header band.",
      type: "hexColor",
      initialValue: "#01190D",
    }),
    defineField({
      name: "headingColor",
      title: "Heading / accent colour",
      description: "Optional accent for the title + primary button.",
      type: "hexColor",
    }),
  ],
  preview: {
    select: { title: "title", layout: "layout", media: "media.asset" },
    prepare: ({ title, layout, media }) => ({
      title: i18nValue(title) || "Header / Hero",
      subtitle: layout ? `Header — ${layout}` : "Header",
      media,
    }),
  },
});
