"use client";

import { useCallback } from "react";
import { set, unset, type StringInputProps } from "sanity";

/**
 * A visual variant picker for the page-builder. Renders a string field's
 * `options.list` as a grid of thumbnail cards (radio behaviour), so a
 * non-technical editor picks a layout/style by seeing a picture of it rather
 * than knowing a code name.
 *
 * Wire it on a block's `layout`/`variant`/`cardStyle` field:
 *   defineField({
 *     name: "layout",
 *     type: "string",
 *     options: {
 *       list: [{ title: "Split", value: "split" }, …],   // titles + values
 *       thumbBase: "/static/blocks/headerBlock",          // → `${thumbBase}-${value}.png`
 *     },
 *     components: { input: VariantSelectInput },
 *   })
 *
 * Thumbnails are generated by scripts/generate-block-thumbnails.mjs and served
 * from /public/static/blocks. Falls back to a labelled card when an image is
 * missing, so it is always usable even before thumbnails exist.
 */

type ListItem = { title?: string; value?: string } | string;

function normalizeList(list: unknown): { title: string; value: string }[] {
  if (!Array.isArray(list)) return [];
  return (list as ListItem[]).map((item) =>
    typeof item === "string"
      ? { title: item, value: item }
      : { title: item.title ?? item.value ?? "", value: item.value ?? "" },
  );
}

export function VariantSelectInput(props: StringInputProps) {
  const { value, onChange, schemaType } = props;
  const options = (schemaType.options ?? {}) as {
    list?: unknown;
    thumbBase?: string;
  };
  const items = normalizeList(options.list);
  const thumbBase = options.thumbBase;

  const select = useCallback(
    (next: string) => onChange(next === value ? unset() : set(next)),
    [onChange, value],
  );

  if (!items.length) return null;

  return (
    <div
      role="radiogroup"
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(140px, 1fr))",
        gap: 10,
      }}
    >
      {items.map((item) => {
        const selected = item.value === value;
        return (
          <button
            key={item.value}
            type="button"
            role="radio"
            aria-checked={selected}
            aria-label={item.title}
            onClick={() => select(item.value)}
            style={{
              display: "flex",
              flexDirection: "column",
              gap: 6,
              padding: 6,
              cursor: "pointer",
              textAlign: "left",
              borderRadius: 6,
              background: selected
                ? "var(--card-focus-ring-color, #2276fc)"
                : "var(--card-bg-color, transparent)",
              border: `2px solid ${
                selected
                  ? "var(--card-focus-ring-color, #2276fc)"
                  : "var(--card-border-color, #e6e8eb)"
              }`,
              transition: "border-color 120ms ease, background 120ms ease",
            }}
          >
            <span
              style={{
                position: "relative",
                display: "block",
                aspectRatio: "16 / 10",
                borderRadius: 4,
                overflow: "hidden",
                background: "var(--card-muted-fg-color, #f2f4f7)",
              }}
            >
              {thumbBase ? (
                // eslint-disable-next-line @next/next/no-img-element
                <img
                  src={`${thumbBase}-${item.value}.png`}
                  alt=""
                  loading="lazy"
                  style={{
                    position: "absolute",
                    inset: 0,
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                  }}
                  onError={(e) => {
                    (e.currentTarget as HTMLImageElement).style.display = "none";
                  }}
                />
              ) : null}
            </span>
            <span
              style={{
                fontSize: 12,
                fontWeight: 500,
                lineHeight: 1.3,
                color: selected
                  ? "var(--card-bg-color, #fff)"
                  : "var(--card-fg-color, inherit)",
              }}
            >
              {item.title}
            </span>
          </button>
        );
      })}
    </div>
  );
}

export default VariantSelectInput;
